spring.application.name=library_management
server.port=8090
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.ksafgatvufocqiuxrfnl
spring.datasource.password=M9yqvBUS1H9G3NeZ

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=TRACE
jwt.secret=c5m0wvcM6tkfeilAmNROwUGLSbj4ZX8q0LnEvVV8pw0=
jwt.expiration-ms=864000006453